[2024-07-19 13:11:54,319: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:11:54,319: ERROR: main: main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
TypeError: main() takes 0 positional arguments but 1 was given
[2024-07-19 13:15:18,273: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:15:18,273: ERROR: main: name 'BoxValueerror' is not defined]
Traceback (most recent call last):
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 22, in read_yaml
    content=yaml.safe_load(yaml_file)
NameError: name 'yaml' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 8, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 25, in read_yaml
    except BoxValueerror:
NameError: name 'BoxValueerror' is not defined
[2024-07-19 13:15:49,571: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:15:49,571: ERROR: main: name 'BoxValueerror' is not defined]
Traceback (most recent call last):
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 22, in read_yaml
    content=yaml.safe_load(yaml_file)
NameError: name 'yaml' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 8, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 25, in read_yaml
    except BoxValueerror:
NameError: name 'BoxValueerror' is not defined
[2024-07-19 13:16:54,864: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:16:54,864: ERROR: main: name 'yaml' is not defined]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 8, in __init__
    self.config=read_yaml(config_filepath)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 28, in read_yaml
    raise e
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 22, in read_yaml
    content=yaml.safe_load(yaml_file)
NameError: name 'yaml' is not defined
[2024-07-19 13:18:07,364: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:18:07,364: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:18:07,364: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:18:07,364: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 25, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 9, in __init__
    self.params=read_yaml(param_filepath)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 27, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-07-19 13:19:27,741: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:19:27,741: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:19:27,741: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:19:27,741: ERROR: main: module 'os' has no attribute 'mkdirs']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 10, in __init__
    create_directories([self.config.artifacts_root])
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 36, in create_directories
    os.mkdirs(path, exist_ok=true)
AttributeError: module 'os' has no attribute 'mkdirs'
[2024-07-19 13:20:16,289: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:20:16,289: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:20:16,289: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:20:16,289: ERROR: main: name 'true' is not defined]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 10, in __init__
    create_directories([self.config.artifacts_root])
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 36, in create_directories
    os.mkdir(path, exist_ok=true)
NameError: name 'true' is not defined
[2024-07-19 13:20:33,928: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:20:33,928: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:20:33,928: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:20:33,928: ERROR: main: 'exist_ok' is an invalid keyword argument for mkdir()]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 11, in main
    config=configuration_manager()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 10, in __init__
    create_directories([self.config.artifacts_root])
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 36, in create_directories
    os.mkdir(path, exist_ok=True)
TypeError: 'exist_ok' is an invalid keyword argument for mkdir()
[2024-07-19 13:22:08,552: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:22:08,552: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:22:08,552: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:22:08,552: INFO: commons: created directory at:artifacts]
[2024-07-19 13:22:08,552: ERROR: main: "'ConfigBox' object has no attribute 'source_url'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'source_url'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'source_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    data_ingestion_config=config.get_data_ingestion_config()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 16, in get_data_ingestion_config
    source_url=config.source_url,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'source_url'"
[2024-07-19 13:30:17,694: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:30:17,694: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:30:17,694: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:30:17,694: INFO: commons: created directory at:artifacts]
[2024-07-19 13:30:17,694: ERROR: main: __init__() got an unexpected keyword argument 'root_dir']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    data_ingestion_config=config.get_data_ingestion_config()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 14, in get_data_ingestion_config
    data__ingestion_config=DataIngestionConfig(
TypeError: __init__() got an unexpected keyword argument 'root_dir'
[2024-07-19 13:34:11,524: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:34:11,540: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:34:11,540: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:34:11,540: INFO: commons: created directory at:artifacts]
[2024-07-19 13:34:11,540: ERROR: main: __init__() got an unexpected keyword argument 'root_dir']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    data_ingestion_config=config.get_data_ingestion_config()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\config\configuration.py", line 14, in get_data_ingestion_config
    data__ingestion_config=DataIngestionConfig(
TypeError: __init__() got an unexpected keyword argument 'root_dir'
[2024-07-19 13:35:26,662: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:35:26,662: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:35:26,662: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:35:26,662: INFO: commons: created directory at:artifacts]
[2024-07-19 13:35:26,662: ERROR: main: type object 'DataIngestionConfig' has no attribute 'download_file']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion=data_ingestion_config.download_file()
AttributeError: type object 'DataIngestionConfig' has no attribute 'download_file'
[2024-07-19 13:38:54,318: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:38:54,318: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:38:54,318: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:38:54,318: INFO: commons: created directory at:artifacts]
[2024-07-19 13:38:54,318: ERROR: main: type object 'DataIngestion' has no attribute 'download_file']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion=DataIngestion.download_file()
AttributeError: type object 'DataIngestion' has no attribute 'download_file'
[2024-07-19 13:40:42,604: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:40:42,604: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:40:42,604: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:40:42,604: INFO: commons: created directory at:artifacts]
[2024-07-19 13:40:42,604: ERROR: main: downloadfile() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion=DataIngestion.downloadfile()
TypeError: downloadfile() missing 1 required positional argument: 'self'
[2024-07-19 13:45:27,752: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:45:27,752: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:45:27,758: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:45:27,758: INFO: commons: created directory at:artifacts]
[2024-07-19 13:45:27,758: ERROR: main: __init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    data_ingestion=DataIngestion()
TypeError: __init__() missing 1 required positional argument: 'config'
[2024-07-19 13:46:48,225: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:46:48,225: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:46:48,225: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:46:48,225: INFO: commons: created directory at:artifacts]
[2024-07-19 13:46:48,225: ERROR: main: type object 'DataIngestionConfig' has no attribute 'source_url']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion.downloadfile()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 23, in downloadfile
    raise e
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 14, in downloadfile
    dataset_url=self.config.source_url
AttributeError: type object 'DataIngestionConfig' has no attribute 'source_url'
[2024-07-19 13:54:04,666: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 13:54:04,668: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 13:54:04,669: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 13:54:04,669: INFO: commons: created directory at:artifacts]
[2024-07-19 13:54:04,669: ERROR: main: type object 'DataIngestionConfig' has no attribute 'source_url']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion.downloadfile()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 23, in downloadfile
    raise e
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 14, in downloadfile
    dataset_url=self.config.source_url
AttributeError: type object 'DataIngestionConfig' has no attribute 'source_url'
[2024-07-19 14:06:23,819: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 14:06:23,819: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 14:06:23,819: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 14:06:23,819: INFO: commons: created directory at:artifacts]
[2024-07-19 14:06:23,819: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-19 14:06:23,819: ERROR: main: type object 'DataIngestionConfig' has no attribute 'source_url']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion.downloadfile()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 23, in downloadfile
    raise e
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\data_ingestion.py", line 14, in downloadfile
    dataset_url=self.config.source_url
AttributeError: type object 'DataIngestionConfig' has no attribute 'source_url'
[2024-07-19 14:07:37,646: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-19 14:07:37,662: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-19 14:07:37,662: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-19 14:07:37,662: INFO: commons: created directory at:artifacts]
[2024-07-19 14:07:37,662: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-19 14:07:37,662: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-19 14:07:48,686: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-19 14:07:48,973: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-22 14:51:14,015: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-22 14:51:14,015: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-22 14:51:14,015: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-22 14:51:14,015: INFO: commons: created directory at:artifacts]
[2024-07-22 14:51:14,015: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-22 14:51:14,015: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 14:51:24,332: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 14:51:24,632: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-22 14:51:24,633: INFO: main: *******************]
[2024-07-22 14:51:24,633: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-22 14:51:24,633: ERROR: main: name 'PrepareBaseModelTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    prepare_base_model = PrepareBaseModelTrainingPipeline()
NameError: name 'PrepareBaseModelTrainingPipeline' is not defined
[2024-07-22 14:57:12,671: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-22 14:57:12,671: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-22 14:57:12,671: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-22 14:57:12,671: INFO: commons: created directory at:artifacts]
[2024-07-22 14:57:12,671: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-22 14:57:12,671: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 14:57:19,584: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 14:57:19,826: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-22 14:57:19,826: INFO: main: *******************]
[2024-07-22 14:57:19,826: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-22 14:57:19,841: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-22 14:57:19,841: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-22 14:57:19,841: INFO: commons: created directory at:artifacts]
[2024-07-22 14:57:19,841: ERROR: main: 'configuration_manager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    prepare_base_model.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'configuration_manager' object has no attribute 'get_prepare_base_model_config'
[2024-07-22 15:00:51,344: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-22 15:00:51,359: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-22 15:00:51,359: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-22 15:00:51,359: INFO: commons: created directory at:artifacts]
[2024-07-22 15:00:51,359: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-22 15:00:51,359: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 15:00:58,041: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-22 15:00:58,312: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-22 15:00:58,312: INFO: main: *******************]
[2024-07-22 15:00:58,312: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-22 15:00:58,312: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-22 15:00:58,312: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-22 15:00:58,312: INFO: commons: created directory at:artifacts]
[2024-07-22 15:00:58,312: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-22 15:01:04,728: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-22 15:01:04,862: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-23 14:47:55,218: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-23 14:47:55,221: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:47:55,224: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:47:55,224: INFO: commons: created directory at:artifacts]
[2024-07-23 14:47:55,225: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-23 14:47:55,225: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 14:48:06,127: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 14:48:06,464: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-23 14:48:06,464: INFO: main: *******************]
[2024-07-23 14:48:06,464: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-23 14:48:06,464: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:48:06,464: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:48:06,464: INFO: commons: created directory at:artifacts]
[2024-07-23 14:48:06,464: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-23 14:48:06,921: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-23 14:48:07,159: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-23 14:48:07,159: INFO: main: *******************]
[2024-07-23 14:48:07,160: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-23 14:48:07,161: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:48:07,162: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:48:07,163: INFO: commons: created directory at:artifacts]
[2024-07-23 14:48:07,164: INFO: commons: created directory at:artifacts\training]
[2024-07-23 14:48:07,164: ERROR: main: local variable 'training' referenced before assignment]
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_03_model_trainer.py", line 18, in main
    training = training(config=training_config)
UnboundLocalError: local variable 'training' referenced before assignment
[2024-07-23 14:51:11,387: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-23 14:51:11,390: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:51:11,391: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:51:11,392: INFO: commons: created directory at:artifacts]
[2024-07-23 14:51:11,392: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-23 14:51:11,393: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 14:51:17,963: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 14:51:18,304: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-23 14:51:18,304: INFO: main: *******************]
[2024-07-23 14:51:18,304: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-23 14:51:18,312: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:51:18,313: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:51:18,313: INFO: commons: created directory at:artifacts]
[2024-07-23 14:51:18,313: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-23 14:51:18,635: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-23 14:51:18,869: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-23 14:51:18,870: INFO: main: *******************]
[2024-07-23 14:51:18,870: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-23 14:51:18,872: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 14:51:18,873: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 14:51:18,874: INFO: commons: created directory at:artifacts]
[2024-07-23 14:51:18,874: INFO: commons: created directory at:artifacts\training]
[2024-07-23 14:51:18,874: ERROR: main: training() takes no arguments]
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_03_model_trainer.py", line 18, in main
    training_1 = training(config=training_config)
TypeError: training() takes no arguments
[2024-07-23 17:28:19,280: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-23 17:28:19,289: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 17:28:19,289: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 17:28:19,289: INFO: commons: created directory at:artifacts]
[2024-07-23 17:28:19,289: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-23 17:28:19,289: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 17:28:27,906: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-23 17:28:28,168: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-23 17:28:28,168: INFO: main: *******************]
[2024-07-23 17:28:28,168: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-23 17:28:28,183: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 17:28:28,183: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 17:28:28,183: INFO: commons: created directory at:artifacts]
[2024-07-23 17:28:28,183: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-23 17:28:28,464: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-23 17:28:28,607: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-23 17:28:28,608: INFO: main: *******************]
[2024-07-23 17:28:28,608: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-23 17:28:28,610: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 17:28:28,612: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 17:28:28,612: INFO: commons: created directory at:artifacts]
[2024-07-23 17:28:28,613: INFO: commons: created directory at:artifacts\training]
[2024-07-23 17:28:44,866: INFO: main: >>>>>> stage Model_training completed <<<<<<

x==========x]
[2024-07-23 17:28:44,867: INFO: main: *******************]
[2024-07-23 17:28:44,867: INFO: main: >>>>>> stage model_Evaluation started <<<<<<]
[2024-07-23 17:28:44,869: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-23 17:28:44,870: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-23 17:28:44,870: INFO: commons: created directory at:artifacts]
[2024-07-23 17:28:44,870: ERROR: main: 'configuration_manager' object has no attribute 'get_evaluation_config']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_04_model_evaluation.py", line 16, in main
    eval_config = config.get_evaluation_config()
AttributeError: 'configuration_manager' object has no attribute 'get_evaluation_config'
[2024-07-24 10:41:58,787: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-24 10:41:58,787: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:41:58,794: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:41:58,794: INFO: commons: created directory at:artifacts]
[2024-07-24 10:41:58,794: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-24 10:41:58,794: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 10:42:12,799: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 10:42:13,126: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-24 10:42:13,126: INFO: main: *******************]
[2024-07-24 10:42:13,126: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 10:42:13,126: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:42:13,126: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:42:13,126: INFO: commons: created directory at:artifacts]
[2024-07-24 10:42:13,126: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-24 10:42:13,611: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 10:42:13,823: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 10:42:13,823: INFO: main: *******************]
[2024-07-24 10:42:13,823: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-24 10:42:13,830: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:42:13,830: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:42:13,830: INFO: commons: created directory at:artifacts]
[2024-07-24 10:42:13,830: INFO: commons: created directory at:artifacts\training]
[2024-07-24 10:42:35,486: INFO: main: >>>>>> stage Model_training completed <<<<<<

x==========x]
[2024-07-24 10:42:35,486: INFO: main: *******************]
[2024-07-24 10:42:35,486: INFO: main: >>>>>> stage model_Evaluation started <<<<<<]
[2024-07-24 10:42:35,486: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:42:35,486: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:42:35,486: INFO: commons: created directory at:artifacts]
[2024-07-24 10:42:42,370: ERROR: main: save_json() got an unexpected keyword argument 'path']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    obj.main()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\pipeline\stage_04_model_evaluation.py", line 18, in main
    evaluation.evaluation()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\model_evaluation.py", line 49, in evaluation
    self.save_score()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\model_evaluation.py", line 53, in save_score
    save_json(path=Path("scores.json"), data=scores)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
TypeError: save_json() got an unexpected keyword argument 'path'
[2024-07-24 10:51:03,188: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-24 10:51:03,191: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:51:03,193: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:51:03,193: INFO: commons: created directory at:artifacts]
[2024-07-24 10:51:03,194: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-24 10:51:03,194: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 10:51:15,330: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 10:51:15,682: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-24 10:51:15,682: INFO: main: *******************]
[2024-07-24 10:51:15,682: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 10:51:15,682: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:51:15,698: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:51:15,698: INFO: commons: created directory at:artifacts]
[2024-07-24 10:51:15,698: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-24 10:51:16,081: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 10:51:16,298: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 10:51:16,299: INFO: main: *******************]
[2024-07-24 10:51:16,299: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-24 10:51:16,301: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:51:16,303: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:51:16,303: INFO: commons: created directory at:artifacts]
[2024-07-24 10:51:16,304: INFO: commons: created directory at:artifacts\training]
[2024-07-24 10:51:40,528: INFO: main: >>>>>> stage Model_training completed <<<<<<

x==========x]
[2024-07-24 10:51:40,528: INFO: main: *******************]
[2024-07-24 10:51:40,528: INFO: main: >>>>>> stage model_Evaluation started <<<<<<]
[2024-07-24 10:51:40,533: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 10:51:40,536: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 10:51:40,536: INFO: commons: created directory at:artifacts]
[2024-07-24 10:51:48,203: INFO: main: >>>>>> stage model_Evaluation completed <<<<<<

x==========x]
[2024-07-24 11:05:33,435: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-07-24 11:05:33,435: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 11:05:33,435: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 11:05:33,451: INFO: commons: created directory at:artifacts]
[2024-07-24 11:05:33,451: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-24 11:05:33,451: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 11:05:40,455: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 11:05:40,789: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-07-24 11:05:40,790: INFO: main: *******************]
[2024-07-24 11:05:40,790: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 11:05:40,792: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 11:05:40,794: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 11:05:40,794: INFO: commons: created directory at:artifacts]
[2024-07-24 11:05:40,795: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-24 11:05:41,152: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 11:05:41,369: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 11:05:41,370: INFO: main: *******************]
[2024-07-24 11:05:41,370: INFO: main: >>>>>> stage Model_training started <<<<<<]
[2024-07-24 11:05:41,370: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 11:05:41,370: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 11:05:41,370: INFO: commons: created directory at:artifacts]
[2024-07-24 11:05:41,376: INFO: commons: created directory at:artifacts\training]
[2024-07-24 11:06:06,124: INFO: main: >>>>>> stage Model_training completed <<<<<<

x==========x]
[2024-07-24 11:06:06,124: INFO: main: *******************]
[2024-07-24 11:06:06,124: INFO: main: >>>>>> stage model_Evaluation started <<<<<<]
[2024-07-24 11:06:06,131: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 11:06:06,131: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 11:06:06,131: INFO: commons: created directory at:artifacts]
[2024-07-24 11:06:16,503: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-24 11:06:16,965: INFO: builder_impl: Assets written to: C:\Users\ishwa\AppData\Local\Temp\tmp5jt_w1lp\model\data\model\assets]
[2024-07-24 11:06:43,946: INFO: main: >>>>>> stage model_Evaluation completed <<<<<<

x==========x]
[2024-07-24 14:03:41,868: INFO: stage_01_data_ingestion: >>>>>> stage Data ingestion Stage started <<<<<<]
[2024-07-24 14:03:41,868: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:03:41,868: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:03:41,868: INFO: commons: created directory at:artifacts]
[2024-07-24 14:03:41,868: INFO: commons: created directory at:artifacts/data_ingestion]
[2024-07-24 14:03:41,868: INFO: data_ingestion: downloading data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 14:03:52,814: INFO: data_ingestion: downloaded data fromhttps://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing in artifacts/data_ingestion/data.zip]
[2024-07-24 14:03:53,119: INFO: stage_01_data_ingestion: >>>>>> stage Data ingestion Stage completed <<<<<<]
[2024-07-24 14:03:58,121: INFO: stage_02_prepare_base_model: *******************]
[2024-07-24 14:03:58,137: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 14:03:58,137: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:03:58,137: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:03:58,137: INFO: commons: created directory at:artifacts]
[2024-07-24 14:03:58,137: INFO: commons: created directory at:artifacts/prepare_base_model]
[2024-07-24 14:03:58,448: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:03:58,688: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-07-24 14:04:02,714: INFO: stage_03_model_trainer: *******************]
[2024-07-24 14:04:02,714: INFO: stage_03_model_trainer: >>>>>> stage Training started <<<<<<]
[2024-07-24 14:04:02,714: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:04:02,714: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:04:02,714: INFO: commons: created directory at:artifacts]
[2024-07-24 14:04:02,714: INFO: commons: created directory at:artifacts\training]
[2024-07-24 14:04:18,519: INFO: stage_03_model_trainer: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-07-24 14:04:23,060: INFO: stage_04_model_evaluation: *******************]
[2024-07-24 14:04:23,060: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-24 14:04:23,060: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:04:23,060: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:04:23,060: INFO: commons: created directory at:artifacts]
[2024-07-24 14:04:30,451: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-07-24 14:04:31,027: INFO: builder_impl: Assets written to: C:\Users\ishwa\AppData\Local\Temp\tmplo21rns4\model\data\model\assets]
[2024-07-24 14:04:53,776: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-24 14:10:14,369: INFO: stage_04_model_evaluation: *******************]
[2024-07-24 14:10:14,369: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-24 14:10:14,369: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:10:14,369: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:10:14,369: INFO: commons: created directory at:artifacts]
[2024-07-24 14:10:19,525: ERROR: stage_04_model_evaluation: name 'path_to_json' is not defined]
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 30, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 18, in main
    evaluation.evaluation()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\model_evaluation.py", line 49, in evaluation
    self.save_score()
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\components\model_evaluation.py", line 53, in save_score
    save_json(path=Path("scores.json"), data=scores)
  File "C:\Users\ishwa\anaconda3\envs\cnnproj\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
  File "c:\users\ishwa\chestcancerdetection\src\cnnclassifier\utils\commons.py", line 47, in save_json
    logger.info(f"json file saved at{path_to_json}")
NameError: name 'path_to_json' is not defined
[2024-07-24 14:13:53,510: INFO: stage_04_model_evaluation: *******************]
[2024-07-24 14:13:53,510: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-07-24 14:13:53,510: INFO: commons: yaml file :config\config.yaml loaded successfully]
[2024-07-24 14:13:53,510: INFO: commons: yaml file :params.yaml loaded successfully]
[2024-07-24 14:13:53,510: INFO: commons: created directory at:artifacts]
[2024-07-24 14:13:58,697: INFO: commons: json file saved atscores.json]
[2024-07-24 14:13:58,697: INFO: commons: json file saved atscores.json]
[2024-07-24 14:13:58,697: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-07-24 22:23:55,156: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.106:8080]
[2024-07-24 22:23:55,156: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-24 22:24:10,817: INFO: _internal: 192.168.0.106 - - [24/Jul/2024 22:24:10] "GET / HTTP/1.1" 200 -]
[2024-07-24 22:42:06,873: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.106:8080]
[2024-07-24 22:42:06,873: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-24 22:42:14,466: INFO: _internal: 192.168.0.106 - - [24/Jul/2024 22:42:14] "GET / HTTP/1.1" 200 -]
[2024-07-24 22:44:26,062: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.106:8080]
[2024-07-24 22:44:26,062: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-07-24 22:44:37,726: INFO: _internal: 192.168.0.106 - - [24/Jul/2024 22:44:37] "GET / HTTP/1.1" 200 -]
